version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
      - echo "Applying Terraform Plan"
      - terraform apply -auto-approve
      - echo "Waiting for 3 minutes before destroying resources"
      - sleep 180
      - echo "Destroying Terraform Resources"
      - terraform destroy -auto-approve